development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: sms_db
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: sms_db
  pool: 5
  username: root
  password: kothanur54
  host: localhost

