development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: sms_db
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: sms_db
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: sms_db
  pool: 5
  username: root
  password: 123456
  host: localhost